version: '3.8'

services:
  api:
    build: 
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped

  # For production with external database, comment out the db service
  # db:
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #   volumes:
  #     - mysql_prod_data:/var/lib/mysql
  #     - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "3306:3306"
  #   restart: unless-stopped

# volumes:
#   mysql_prod_data: