version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD:-devpassword123}
      - DB_NAME=dea
      - DB_PORT=3306
      - SECRET_KEY=${SECRET_KEY:-change-this-secret}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-devpassword123}
      - MYSQL_DATABASE=dea
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data: